### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by iphydf** [eddyxu/cpp-coveralls#108]
I'm getting an SSL cert error. This error does not happen on the Scala (sbt-coveralls) plugin. It might be a coveralls issue, but it started happening a few days ago.

```
/home/travis/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/home/travis/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/home/travis/.local/bin/coveralls", line 9, in <module>
    load_entry_point('cpp-coveralls==0.3.12', 'console_scripts', 'coveralls')()
  File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/__init__.py", line 105, in run
    return report.post_report(cov_report)
  File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/report.py", line 12, in post_report
    response = requests.post(URL, files={'json_file': json.dumps(coverage)})
  File "/home/travis/.local/lib/python2.7/site-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/travis/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/travis/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/travis/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/travis/.local/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by iphydf** [comment]
This hack fixes it: https://github.com/TokTok/c-toxcore/pull/377
I think you can use it to fix it properly.

**Comment by mkfifo** [comment]
I also did the same fix for my `.travis.yml` file to have cpp-coveralls run cleanly under travis
https://github.com/mkfifo/icarus/commit/03a9fd2f0eec1125f04a7d6011c539ae1223fdc0

You can see these instructions by visiting 
https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2

**Comment by eddyxu** [comment]
@mkfifo  Should I put "urllib3[secure]" into ```requirements.txt```?

**Comment by mkfifo** [comment]
@eddyxu I haven't tested that yet, but I have prepared a PR doing just that.

**Comment by eddyxu** [comment]
Hi, @iphydf  Can you try: 

```pip install git+git@github.com:eddyxu/cpp-coveralls.git```

If it works for you, I will issue a new release.

**Comment by iphydf** [comment]
https://travis-ci.org/TokTok/c-toxcore/jobs/189768896#L693

Perhaps the version of pip on travis is not recent enough?

**Comment by mkfifo** [comment]
@iphydf is this still happening for you with HEAD ?
