### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '917*'

### ISSUE THREAD

**Issue by kammce** [eddyxu/cpp-coveralls#130]
Everytime I run coveralls in Travis CI I get the following error:
```
Traceback (most recent call last):
  File "/home/travis/.local/bin/coveralls", line 11, in <module>
    sys.exit(run())
  File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/__init__.py", line 97, in run
    cov_report = coverage.collect(args)
  File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/coverage.py", line 450, in collect
    src_report['coverage'] = parse_gcov_file(args, fobj, gcov_path)
  File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/coverage.py", line 288, in parse_gcov_file
    coverage.append(int(cov_num))
ValueError: invalid literal for int() with base 10: '917*'
```

The Travis-CI job can be found here:
https://travis-ci.org/kammce/SJSU-Dev2/jobs/405812286

**Comment by mandeep** [comment]
I started seeing this today on my build:
```
Traceback (most recent call last):
  File "/home/travis/.local/bin/coveralls", line 11, in <module>
    sys.exit(run())
  File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/__init__.py", line 97, in run
    cov_report = coverage.collect(args)
  File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/coverage.py", line 450, in collect
    src_report['coverage'] = parse_gcov_file(args, fobj, gcov_path)
  File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/coverage.py", line 288, in parse_gcov_file
    coverage.append(int(cov_num))
ValueError: invalid literal for int() with base 10: '10*'
```

**Comment by bassosimone** [comment]
@eddyxu it would be nice if you could cut a new release including the above mentioned fix :-)

**Comment by eddyxu** [comment]
Sorry for late reply. I will include this in 0.4.1 release.
