### ISSUE TITLE
pip install failure on ubuntu/trusty64

### ISSUE THREAD

**Issue by thirtytwobits** [eddyxu/cpp-coveralls#133]
I'm unable to install cpp-coveralls on my vagrant host. I get the following exception when executing the `sudo pip3 install -U cpp-coveralls` command:

```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1091, in prepare_files
    req_to_install.check_if_exists()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 811, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(self.req)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 479, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 355, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
IndexError: list index out of range
```

My provisioning script is:

```
sudo apt-get update
sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
sudo apt-get update
sudo apt-get -y install cmake
sudo apt-get -y install python3
sudo apt-get -y install python3-pip
sudo apt-get -y install git
sudo apt-get -y install g++-5;
sudo apt-get -y install gcc-arm-embedded
sudo apt-get -y purge python-openssl
sudo apt-get -y install libffi-dev
sudo apt-get -y install libssl-dev

sudo pip3 install --upgrade setuptools
sudo pip3 install pyopenssl
sudo pip3 install pyyaml
sudo pip3 install -U cpp-coveralls
```

**Comment by thirtytwobits** [comment]
Adding more context from the logs

```
Installed version (2.7) is most up-to-date (past versions: 2.7, 2.7, 2.6, 2.6, 2.5, 2.5)
Requirement already up-to-date: idna<2.8,>=2.5 in /usr/local/lib/python3.4/dist-packages (from requests->cpp-coveralls)
Downloading/unpacking certifi>=2017.4.17 (from requests->cpp-coveralls)
  Getting page https://pypi.python.org/simple/certifi/
  URLs to search for versions for certifi>=2017.4.17 (from requests->cpp-coveralls):
  * https://pypi.python.org/simple/certifi/
  Analyzing links from page https://pypi.org/simple/certifi/
    Found link https://files.pythonhosted.org/packages/55/bf/e1094f052b5932a452b12ac5a6c229f3d7dbf41a66cfc8d5832fe3fb6463/certifi-0.0.1.tar.gz#sha256=a6f0d79b2b63a43c71bc128929be3a17bdf5d0a5f74208d7ad9563b3bf8210e9 (from https://pypi.org/simple/certifi/), version: 0.0.1
    Found link https://files.pythonhosted.org/packages/0c/4d/6e036d6158e533499272f7b82d0ffa115ecc7c930994475b7bf8f4047489/certifi-0.0.2.tar.gz#sha256=678b7a44338228d55bc4569a575b4734bbbcb9da109328f3b10e3435ec6abdee (from https://pypi.org/simple/certifi/), version: 0.0.2
    Found link https://files.pythonhosted.org/packages/17/3d/7d037b5aadde37d95c067e5b26f064ae53f791201a89b5b38ee315409264/certifi-0.0.3.tar.gz#sha256=1418bce4a32cd409b9766a7c92556be4d23f287da581945be4076eea299fbeac (from https://pypi.org/simple/certifi/), version: 0.0.3
    Found link https://files.pythonhosted.org/packages/cd/b9/ad866737dfde6b459fa3188b13d249e50101fa06bab408e6d9e5029b6838/certifi-0.0.4.tar.gz#sha256=8aed314d0d133c70fd9c56ee13cabe0910c0f6ff423da266841512af0e3d68c4 (from https://pypi.org/simple/certifi/), version: 0.0.4
    Found link https://files.pythonhosted.org/packages/84/b9/a5aac1c71b154f18dad87b39e42a118a538ce4f95fe10f3f651b0c3d0ac2/certifi-0.0.5.tar.gz#sha256=c1c47a7545e39e19357d51c2e5291de158508024658d6860815359566ac65c02 (from https://pypi.org/simple/certifi/), version: 0.0.5
    Found link https://files.pythonhosted.org/packages/76/4a/92995898df84d15c42d49e38b814caa94502cbf28be9b9732703303f2107/certifi-0.0.6.tar.gz#sha256=e839718ce80daa9853b1f47a333757d4a22cdf422e2fd8de5e579d5634a89585 (from https://pypi.org/simple/certifi/), version: 0.0.6
    Found link https://files.pythonhosted.org/packages/43/10/aafebf9677ccec8b227f15eef20a4aac65fbff7f14fc9462f06855fecdd2/certifi-0.0.7.tar.gz#sha256=6dec7d3c6f3d4ed0a50fb15f8fd41c0bb1b17998eb8c103d0f34d61c19061e36 (from https://pypi.org/simple/certifi/), version: 0.0.7
    Found link https://files.pythonhosted.org/packages/38/70/d777da670969367780cb0cb66f43799e17e050dcdeb0fa4e26189519f9f2/certifi-0.0.8.tar.gz#sha256=46ecf5f7526a08cc1f8bc8232adf0cffce046f46ceff95539daec42ebc4849ef (from https://pypi.org/simple/certifi/), version: 0.0.8
    Found link https://files.pythonhosted.org/packages/eb/fe/3ba38b686003664a75c01c42c6f1be02f9837d007c0f15727e6f8f2040a3/certifi-1.0.0.tar.gz#sha256=d4f8e89c9e709f67221bf21231d0fa66a00d3712bcb69d4b5aef3705339c8dcd (from https://pypi.org/simple/certifi/), version: 1.0.0
    Found link https://files.pythonhosted.org/packages/4e/58/86422944e1f228a4e90c291388bf69675826c995f163b2894541365f1f0e/certifi-1.0.1-py2.py3-none-any.whl#sha256=44964ac783fca598e723da5fa2ef3631b5b2f94f445749bfc6043d4afb20de75 (from https://pypi.org/simple/certifi/), version: 1.0.1
    Found link https://files.pythonhosted.org/packages/ff/3a/ec07518540a090d463aa20c615a170d52a3633057fde480bd462883a0de2/certifi-1.0.1.tar.gz#sha256=f2c18c7edd349ec10378ef43ff16f81ae1d0af61d5d2858a8b383e8f6814a9cc (from https://pypi.org/simple/certifi/), version: 1.0.1
    Found link https://files.pythonhosted.org/packages/c1/ed/4a424a55f77679700452972e583393b64160583c80ffa893b4be9391f3ae/certifi-14.05.14.tar.gz#sha256=1e1bcbacd6357c151ae37cf0290dcc809721d32ce21fd6b7339568f3ddef1b69 (from https://pypi.org/simple/certifi/), version: 14.05.14
    Found link https://files.pythonhosted.org/packages/86/35/9758a67004a266047c779ae40a3d937869bfc6fc3422f6c606b8afbc9d23/certifi-2015.04.28-py2.py3-none-any.whl#sha256=268fa00c27de756d71663dd61f73a4a8d8727569bb1b474b2ce6020553826872 (from https://pypi.org/simple/certifi/), version: 2015.04.28
    Found link https://files.pythonhosted.org/packages/4a/41/52617061e93551d5c8041b70d35db395ad647cc356beb764cd9b278e3114/certifi-2015.04.28.tar.gz#sha256=99785e6cf715cdcde59dee05a676e99f04835a71e7ced201ca317401c322ba96 (from https://pypi.org/simple/certifi/), version: 2015.04.28
    Found link https://files.pythonhosted.org/packages/c6/aa/85432217f85f1553dc0926a3e00b48e00819b80097dd056e482c19766f11/certifi-2015.9.6-py2.py3-none-any.whl#sha256=499d154e26c642108248be45b4e09d3b978d2e7c6a72e0a147a2e81448a61a7d (from https://pypi.org/simple/certifi/), version: 2015.9.6
    Found link https://files.pythonhosted.org/packages/e2/ec/ab8442e4d6cf92ea4df67ed81e078bd6a9e092c96ffcd03dbd910e1eb389/certifi-2015.9.6.tar.gz#sha256=7e5646f75d2779719b3400c009e3461f921823e4592657f8e00fb2b6e14b8b92 (from https://pypi.org/simple/certifi/), version: 2015.9.6
    Found link https://files.pythonhosted.org/packages/cc/7f/fb45b6c47ff3a1e119b8fa0aec4a9d1812f0c9f774d877eca582065ef21e/certifi-2015.9.6.1-py2.py3-none-any.whl#sha256=4cbb1f8b30948895f36bb94402598506808833747e0a2e1ca5b1f152ff341da4 (from https://pypi.org/simple/certifi/), version: 2015.9.6.1
    Found link https://files.pythonhosted.org/packages/d6/8d/700b62e1cbcd0264450b8bb476757808ef2c3f6060ee552c3717d010b616/certifi-2015.9.6.1.tar.gz#sha256=f924457bd89178e565fe1b90359d90639f524e7da1a99988292474f52defbf34 (from https://pypi.org/simple/certifi/), version: 2015.9.6.1
    Found link https://files.pythonhosted.org/packages/58/41/b16d4787c30bfb27d608fd2383ab2a7823afa0491fa16df04336d7b7519b/certifi-2015.9.6.2-py2.py3-none-any.whl#sha256=7486e08ffd0a9bea8c66e76fd1f0f0150294c572e78cb16b14d8589beafd3564 (from https://pypi.org/simple/certifi/), version: 2015.9.6.2
    Found link https://files.pythonhosted.org/packages/63/71/422814652028afbff99347da9f3d102f53113a1d2389e255a2dde15c5d8d/certifi-2015.9.6.2.tar.gz#sha256=dc3a2b2d9d1033dbf27586366ae61b9d7c44d8c3a6f29694ffcbb0618ea7aea6 (from https://pypi.org/simple/certifi/), version: 2015.9.6.2
    Found link https://files.pythonhosted.org/packages/a5/2b/83904abc08c3d95808d098163b049e923cbf9fa04f6fa5c0f3750959da8e/certifi-2015.11.20-py2.py3-none-any.whl#sha256=12e141bb3e0f1b3ea4d5a8af804fc59ff94d5ece040cf8d22232ddf87eec096b (from https://pypi.org/simple/certifi/), version: 2015.11.20
    Found link https://files.pythonhosted.org/packages/c5/8a/d007319d95bd2424adb3f2a41ffb29de76f2c07b3dd5fd98f3651f9a14f5/certifi-2015.11.20.tar.gz#sha256=7168668372f07219439e82878b484d6216ff63224fd4e7ff4f39c56ad0b487de (from https://pypi.org/simple/certifi/), version: 2015.11.20
    Found link https://files.pythonhosted.org/packages/df/21/86903664789d010c7693523aa44cd6f96f9d60c7bc813761ff3db5fa8aad/certifi-2015.11.20.1-py2.py3-none-any.whl#sha256=ad86683448f7483d4147a64d96856e551734e594c4563747e9fbe2368df13d3f (from https://pypi.org/simple/certifi/), version: 2015.11.20.1
    Found link https://files.pythonhosted.org/packages/08/59/d39d98454a4fd2c9e0955590398bcfc4047f8e6dde00d7731cefdb32b403/certifi-2015.11.20.1.tar.gz#sha256=30b0a7354a1b32caa8b4705d3f5fb2dadefac7ba4bf8af8a2176869f93e38f16 (from https://pypi.org/simple/certifi/), version: 2015.11.20.1
    Found link https://files.pythonhosted.org/packages/db/60/1ed0106bde7b14b363b15b17cc308aad93ba57d3582570f3ad7180ae0fae/certifi-2016.2.28-py2.py3-none-any.whl#sha256=75c33d546e0a732a4606749cbadcd81929f30d8b814061ca93cde49933dbb860 (from https://pypi.org/simple/certifi/), version: 2016.2.28
    Found link https://files.pythonhosted.org/packages/5c/f8/f6c54727c74579c6bbe5926f5deb9677c5810a33e11da58d1a4e2d09d041/certifi-2016.2.28.tar.gz#sha256=5e8eccf95924658c97b990b50552addb64f55e1e3dfe4880456ac1f287dc79d0 (from https://pypi.org/simple/certifi/), version: 2016.2.28
    Found link https://files.pythonhosted.org/packages/65/da/116b7b175ecdb089406ec24238d1fe668b52d3f25e4e7ba88983807eac6a/certifi-2016.8.2-py2.py3-none-any.whl#sha256=c6290b32cfccf569a621d0449fcaf9283a3e0c77108bc808545b41c779d42e0a (from https://pypi.org/simple/certifi/), version: 2016.8.2
    Found link https://files.pythonhosted.org/packages/60/d8/e4dbd7239f1dd3854135949cc2cc8344602b1545a7929b7bf652ac69fbb6/certifi-2016.8.2.tar.gz#sha256=65ddc34fd9c8509851031d7075b8325393b87e6dbe5875a723959a20266d7a41 (from https://pypi.org/simple/certifi/), version: 2016.8.2
    Found link https://files.pythonhosted.org/packages/dd/ed/e9bf6a9dc79e23c68385c4ea692f0e9e1a7880518872564f88be013b552f/certifi-2016.8.8-py2.py3-none-any.whl#sha256=04f0e6677e6a5a64ba83ade859bcdda254c1ccf58545eb72bc2067f51a01873c (from https://pypi.org/simple/certifi/), version: 2016.8.8
    Found link https://files.pythonhosted.org/packages/41/bf/88a3269c7c95fc94a2c581c4b1b3d3ec21af7a268d6a3a4e54578adccfd6/certifi-2016.8.8.tar.gz#sha256=99864ed602d8a9d212e339b15ffa438895002eda7b7db20dca5309dac9605ae9 (from https://pypi.org/simple/certifi/), version: 2016.8.8
    Found link https://files.pythonhosted.org/packages/34/21/ebb383f944dfc3a14461ee021089da90477be919a5554117c184ae3d44be/certifi-2016.8.31-py2.py3-none-any.whl#sha256=172844a3e2896c924e6aa2657b2e56586a724f27edd0e9592be9353f3a3f6c73 (from https://pypi.org/simple/certifi/), version: 2016.8.31
    Found link https://files.pythonhosted.org/packages/1c/d1/0133a5084f0d17db0270c6061e824a11b0e417d743f5ff4c594f4090ed89/certifi-2016.8.31.tar.gz#sha256=f7708a42d86f29ccc7c8c4ff9d34a8d854d8d78eb2973d1f28406bb43d6b8919 (from https://pypi.org/simple/certifi/), version: 2016.8.31
    Found link https://files.pythonhosted.org/packages/a2/35/b7b457c95fdd661d4c179201e9e58a2181934695943b08ccfcba09284b4e/certifi-2016.9.26-py2.py3-none-any.whl#sha256=a60073d7bb5cb01671877efda875e8dab755b98baedfbb9b8b3d9be2d52ad022 (from https://pypi.org/simple/certifi/), version: 2016.9.26
    Found link https://files.pythonhosted.org/packages/4f/75/e1bc6e363a2c76f8d7e754c27c437dbe4086414e1d6d2f6b2a3e7846f22b/certifi-2016.9.26.tar.gz#sha256=8275aef1bbeaf05c53715bfc5d8569bd1e04ca1e8e69608cc52bcaac2604eb19 (from https://pypi.org/simple/certifi/), version: 2016.9.26
    Found link https://files.pythonhosted.org/packages/21/f7/7bb6b1c5ba1db21515950bc16b22cd7ef7d27024100f326a19921efd2ce0/certifi-2017.1.23-py2.py3-none-any.whl#sha256=f74a224a9860fd5a2e9757230a7ea3eba82d6d46914780abc18e70c8b58d4bf8 (from https://pypi.org/simple/certifi/), version: 2017.1.23
    Found link https://files.pythonhosted.org/packages/b6/fa/ca682d5ace0700008d246664e50db8d095d23750bb212c0086305450c276/certifi-2017.1.23.tar.gz#sha256=81877fb7ac126e9215dfb15bfef7115fdc30e798e0013065158eed0707fd99ce (from https://pypi.org/simple/certifi/), version: 2017.1.23
    Found link https://files.pythonhosted.org/packages/eb/01/c1f58987b777d6c4ec535b4e004a4a07bfc9db06f0c7533367ca6da8f2a6/certifi-2017.4.17-py2.py3-none-any.whl#sha256=f4318671072f030a33c7ca6acaef720ddd50ff124d1388e50c1bda4cbd6d7010 (from https://pypi.org/simple/certifi/), version: 2017.4.17
    Found link https://files.pythonhosted.org/packages/dd/0e/1e3b58c861d40a9ca2d7ea4ccf47271d4456ae4294c5998ad817bd1b4396/certifi-2017.4.17.tar.gz#sha256=f7527ebf7461582ce95f7a9e03dd141ce810d40590834f4ec20cddd54234c10a (from https://pypi.org/simple/certifi/), version: 2017.4.17
    Found link https://files.pythonhosted.org/packages/dc/ec/38df4e406cfca294fd6e242ea38bd943f47885d95e4dbf1783146f80e391/certifi-2017.7.27-py2.py3-none-any.whl#sha256=f0c0494d4a43fc862826a8ac731538ac68120524d4438e864a1ce2a2916e495d (from https://pypi.org/simple/certifi/), version: 2017.7.27
    Found link https://files.pythonhosted.org/packages/fa/70/bf24052d94f00bfdb70ac70840bfa1ba61e6d56ee7da5f62ecbca743c87e/certifi-2017.7.27.tar.gz#sha256=a7e03cbaf96baad108e34602848d0e4f04e59185325a61e63c96fcf67cee5fcd (from https://pypi.org/simple/certifi/), version: 2017.7.27
    Found link https://files.pythonhosted.org/packages/40/66/06130724e8205fc8c105db7edb92871c7fff7d31324d7f4405c762624a43/certifi-2017.7.27.1-py2.py3-none-any.whl#sha256=54a07c09c586b0e4c619f02a5e94e36619da8e2b053e20f594348c0611803704 (from https://pypi.org/simple/certifi/), version: 2017.7.27.1
    Found link https://files.pythonhosted.org/packages/20/d0/3f7a84b0c5b89e94abbd073a5f00c7176089f526edb056686751d5064cbd/certifi-2017.7.27.1.tar.gz#sha256=40523d2efb60523e113b44602298f0960e900388cf3bb6043f645cf57ea9e3f5 (from https://pypi.org/simple/certifi/), version: 2017.7.27.1
    Found link https://files.pythonhosted.org/packages/29/9b/25ef61e948321296f029f53c9f67cc2b54e224db509eb67ce17e0df6044a/certifi-2017.11.5-py2.py3-none-any.whl#sha256=244be0d93b71e93fc0a0a479862051414d0e00e16435707e5bf5000f92e04694 (from https://pypi.org/simple/certifi/), version: 2017.11.5
    Found link https://files.pythonhosted.org/packages/23/3f/8be01c50ed24a4bd6b8da799839066ce0288f66f5e11f0367323467f0cbc/certifi-2017.11.5.tar.gz#sha256=5ec74291ca1136b40f0379e1128ff80e866597e4e2c1e755739a913bbc3613c0 (from https://pypi.org/simple/certifi/), version: 2017.11.5
    Found link https://files.pythonhosted.org/packages/fa/53/0a5562e2b96749e99a3d55d8c7df91c9e4d8c39a9da1f1a49ac9e4f4b39f/certifi-2018.1.18-py2.py3-none-any.whl#sha256=14131608ad2fd56836d33a71ee60fa1c82bc9d2c8d98b7bdbc631fe1b3cd1296 (from https://pypi.org/simple/certifi/), version: 2018.1.18
    Found link https://files.pythonhosted.org/packages/15/d4/2f888fc463d516ff7bf2379a4e9a552fef7f22a94147655d9b1097108248/certifi-2018.1.18.tar.gz#sha256=edbc3f203427eef571f79a7692bb160a2b0f7ccaa31953e99bd17e307cf63f7d (from https://pypi.org/simple/certifi/), version: 2018.1.18
    Found link https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl#sha256=9fa520c1bacfb634fa7af20a76bcbd3d5fb390481724c597da32c719a7dca4b0 (from https://pypi.org/simple/certifi/), version: 2018.4.16
    Found link https://files.pythonhosted.org/packages/4d/9c/46e950a6f4d6b4be571ddcae21e7bc846fcbb88f1de3eff0f6dd0a6be55d/certifi-2018.4.16.tar.gz#sha256=13e698f54293db9f89122b0581843a782ad0934a4fe0172d2a980ba77fc61bb7 (from https://pypi.org/simple/certifi/), version: 2018.4.16
    Found link https://files.pythonhosted.org/packages/16/1f/50d729c104b21c1042aa51560da6141d1cab476ba7015d92b2111c8db841/certifi-2018.8.13-py2.py3-none-any.whl#sha256=b6e8b28b2b7e771a41ecdd12d4d43262ecab52adebbafa42c77d6b57fb6ad3a4 (from https://pypi.org/simple/certifi/), version: 2018.8.13
    Found link https://files.pythonhosted.org/packages/53/0d/d1d13a63563cc50a27b310f5612645bef06d29a5022a7e79ac659dd0fc50/certifi-2018.8.13.tar.gz#sha256=4c1d68a1408dd090d2f3a869aa94c3947cc1d967821d1ed303208c9f41f0f2f4 (from https://pypi.org/simple/certifi/), version: 2018.8.13
    Found link https://files.pythonhosted.org/packages/df/f7/04fee6ac349e915b82171f8e23cee63644d83663b34c539f7a09aed18f9e/certifi-2018.8.24-py2.py3-none-any.whl#sha256=456048c7e371c089d0a77a5212fb37a2c2dce1e24146e3b7e0261736aaeaa22a (from https://pypi.org/simple/certifi/), version: 2018.8.24
    Found link https://files.pythonhosted.org/packages/e1/0f/f8d5e939184547b3bdc6128551b831a62832713aa98c2ccdf8c47ecc7f17/certifi-2018.8.24.tar.gz#sha256=376690d6f16d32f9d1fe8932551d80b23e9d393a8578c5633a2ed39a64861638 (from https://pypi.org/simple/certifi/), version: 2018.8.24
    Found link https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl#sha256=339dc09518b07e2fa7eda5450740925974815557727d6bd35d319c1524a04a4c (from https://pypi.org/simple/certifi/), version: 2018.10.15
    Found link https://files.pythonhosted.org/packages/41/b6/4f0cefba47656583217acd6cd797bc2db1fede0d53090fdc28ad2c8e0716/certifi-2018.10.15.tar.gz#sha256=6d58c986d22b038c8c0df30d639f23a3e6d172a05c3583e766f4c0b785c0986a (from https://pypi.org/simple/certifi/), version: 2018.10.15
```
(ignored links omitted)
```
  Using version 2018.10.15 (newest of versions: 2018.10.15, 2018.10.15, 2018.8.24, 2018.8.24, 2018.8.13, 2018.8.13, 2018.4.16, 2018.4.16, 2018.1.18, 2018.1.18, 2017.11.5, 2017.11.5, 2017.7.27.1, 2017.7.27.1, 2017.7.27, 2017.7.27, 2017.4.17, 2017.4.17)
  Downloading from URL https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl#sha256=339dc09518b07e2fa7eda5450740925974815557727d6bd35d319c1524a04a4c (from https://pypi.org/simple/certifi/)
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1091, in prepare_files
    req_to_install.check_if_exists()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 811, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(self.req)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 479, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 355, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
IndexError: list index out of range
```

**Comment by thirtytwobits** [comment]
I also tried manually installing dependencies and I get the same error trying to install urllib3[secure] so it's probably that package. Unfortunately this seems to prevent us from using coveralls.

**Comment by eddyxu** [comment]
Thanks for reporting this, looking into it

**Comment by eddyxu** [comment]
Can you use python2 to install coveralls for now.

urllib3[secure] does not exist for python3

**Comment by thirtytwobits** [comment]
As far as I can tell cpp-coveralls is completely broken for python2 on Ubuntu 14. I got errors in setuptools then upgraded that to get more errors (index out of range) in OpenSSL. 

I'm going to upgrade to 18 and try again.
