### ISSUE TITLE
FIleNotFoundError with invalid path

### ISSUE THREAD

**Issue by jwillemsen** [eddyxu/cpp-coveralls#148]
When using coveralls on [AXCIOMA](https://github.com/RemedyIT/axcioma) we get a FileNotFoundError with a path which is not valid

```
Traceback (most recent call last):
  File "/home/johnny/.local/bin/coveralls", line 11, in <module>
    load_entry_point('cpp-coveralls==0.4.2', 'console_scripts', 'coveralls')()
  File "/home/johnny/.local/lib/python3.7/site-packages/cpp_coveralls/__init__.py", line 97, in run
    cov_report = coverage.collect(args)
  File "/home/johnny/.local/lib/python3.7/site-packages/cpp_coveralls/coverage.py", line 455, in collect
    with io.open(source_file_path, mode='rb') as src_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/johnny/ACE/coveralls/axcioma/ACE/ACE/protocols/protocols/ace/INet/ConnectionCache.inl'
```

The path `/home/johnny/ACE/coveralls/axcioma/ACE/ACE/protocols/protocols/ace/INet/ConnectionCache.inl` should be just with one protocols in it.

This can be reproduced by executing the following steps:

```
git clone https://github.com/RemedyIT/axcioma
cd axcioma/
bin/brix11 bootstrap
bin/brix11 -E configure
```
Now open ACE/ACE/include/makeinclude/platform_macros.GNU and add `gcov=1` as first line in this file and save it

```
bin/brix11 gen build workspace.mwc 
bin/brix11 make
bin/brix11 gen build taox11/tests
bin/brix11 make -N taox11/tests
bin/brix11 run list -l taox11/bin/taox11_tests.lst -r taox11/
coveralls --goc-options `\-lp`
```
All environment values which are set during the build can be easily printed using
```
bin/brix11 env
```

**Comment by jwillemsen** [comment]
We put all object files in a subdirectory, but adding the following lines to the end of ACE/ACE/include/makeinclude/platform_macros.GNU they are put in the same directory but that results in the same error but now in a different directory where the path is not correct, /home/johnny/ACE/coveralls/axcioma/include/ast_typedef.h should be /home/johnny/ACE/coveralls/axcioma/ACE/TAO/TAO_IDL/include/ast_typedef.h

```
VDIR=
VSHDIR=
```

The new error

```
Traceback (most recent call last):
  File "/home/johnny/.local/bin/coveralls", line 11, in <module>
    load_entry_point('cpp-coveralls==0.4.2', 'console_scripts', 'coveralls')()
  File "/home/johnny/.local/lib/python3.7/site-packages/cpp_coveralls/__init__.py", line 97, in run
    cov_report = coverage.collect(args)
  File "/home/johnny/.local/lib/python3.7/site-packages/cpp_coveralls/coverage.py", line 455, in collect
    with io.open(source_file_path, mode='rb') as src_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/johnny/ACE/coveralls/axcioma/include/ast_typedef.h'
```
