### ISSUE TITLE
Failed to see coverage results on Coveralls

### ISSUE THREAD

**Issue by vahancho** [eddyxu/cpp-coveralls#154]
From some point my [C++ project](https://github.com/vahancho/erkir) build (Travis-CI) started to fail to upload coverage reports to Coveralls. From the build log it looks like `cpp_coveralls` throws unhandled exception with the fallowing stack trace:

Traceback (most recent call last):

  | File "/home/travis/.local/bin/coveralls", line 11, in <module>
  | sys.exit(run())
  | File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/__init__.py", line 106, in run
  | return report.post_report(cov_report, args)
  | File "/home/travis/.local/lib/python2.7/site-packages/cpp_coveralls/report.py", line 13, in post_report
  | verify=(not args.skip_ssl_verify))
  | File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
  | return request('post', url, data=data, **kwargs)
  | File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
  | return session.request(method=method, url=url, **kwargs)
  | File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
  | resp = self.send(prep, **send_kwargs)
  | File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
  | r = adapter.send(request, **kwargs)
  | File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
  | raise SSLError(e)
  | requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
  | travis_time:end:198bc754:start=1591341443382617895,finish=1591341443592382860,duration=209764965,event=after_success

**Comment by tueda** [comment]
Same here: vermaseren/form#360
